version: "3.5"

services:
  db:
    container_name: db-local
    ports:
      - "5433:5432"
    image: postgres:9.6-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_USER: shopingcart
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - shopingcart

  db-migrate:
    container_name: db-migrate-shopingcart-local
    image: migrate/migrate:v4.6.2
    restart: "on-failure"
    command: ["-path", "/migrations", "-database",  "postgres://shopingcart:@db:5432/shopingcart?sslmode=disable", "up"]
    volumes:
      - ./data/migrations/:/migrations
    networks:
      - shopingcart
  
  go:
    container_name: go-local
    build:
      context: .
      dockerfile: dockerfile
    restart: "on-failure"
    ports:
      - "4000:4000"
    environment:
      TZ: Asia/Singapore
      DATABASE_URL: postgres://shopingcart:@db:5432/shopingcart?sslmode=disable
      PORT: 4000
      JWT_EXPIRES_SECONDS: 36000
    volumes:
      - api-go-build-cache:/root/.cache/go-build
    networks:
      - shopingcart

  alpine:
    container_name: alpine-local
    image: alpine
    restart: "no"
    networks:
      - shopingcart
  
networks:
  shopingcart:

volumes:
  api-go-build-cache:
    name: shopingcart-api-go-build-cache-dev