pkgname="orm"
no-tests="true"
output="internal/orm"
[psql]
  dbname="shopingcart"
  host="localhost"
  port=5433
  user="shopingcart"
  pass=""
  sslmode="disable"
  whitelist=["users", "products", "stocks", "product_discounts", "product_combo_discount", "carts", "cart_items"]
  schema="public"