pkgname="orm"
no-tests="true"
output="internal/orm"
[psql]
  dbname="shopingcart"
  host="localhost"
  port=5433
  user="shopingcart"
  pass=""
  sslmode="disable"
  whitelist=["users", "products", "stocks", "discounts", "discount_rules", "carts", "cart_items", "coupons", "cart_coupons"]
  schema="public"