// Code generated by SQLBoiler 4.3.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	CartItems            string
	Carts                string
	ProductComboDiscount string
	ProductDiscounts     string
	Products             string
	Stocks               string
	Users                string
}{
	CartItems:            "cart_items",
	Carts:                "carts",
	ProductComboDiscount: "product_combo_discount",
	ProductDiscounts:     "product_discounts",
	Products:             "products",
	Stocks:               "stocks",
	Users:                "users",
}
