// Code generated by SQLBoiler 4.3.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	CartCoupons   string
	CartItems     string
	Carts         string
	Coupons       string
	DiscountRules string
	Discounts     string
	OrderCoupons  string
	OrderDiscount string
	OrderItems    string
	Orders        string
	Products      string
	Stocks        string
	Users         string
}{
	CartCoupons:   "cart_coupons",
	CartItems:     "cart_items",
	Carts:         "carts",
	Coupons:       "coupons",
	DiscountRules: "discount_rules",
	Discounts:     "discounts",
	OrderCoupons:  "order_coupons",
	OrderDiscount: "order_discount",
	OrderItems:    "order_items",
	Orders:        "orders",
	Products:      "products",
	Stocks:        "stocks",
	Users:         "users",
}
