// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ProductComboPackage is an object representing the database table.
type ProductComboPackage struct {
	ID        int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *productComboPackageR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L productComboPackageL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ProductComboPackageColumns = struct {
	ID        string
	Name      string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Name:      "name",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var ProductComboPackageWhere = struct {
	ID        whereHelperint64
	Name      whereHelperstring
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: "\"product_combo_packages\".\"id\""},
	Name:      whereHelperstring{field: "\"product_combo_packages\".\"name\""},
	CreatedAt: whereHelpertime_Time{field: "\"product_combo_packages\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"product_combo_packages\".\"updated_at\""},
}

// ProductComboPackageRels is where relationship names are stored.
var ProductComboPackageRels = struct {
	ComboPackageProductDiscounts string
}{
	ComboPackageProductDiscounts: "ComboPackageProductDiscounts",
}

// productComboPackageR is where relationships are stored.
type productComboPackageR struct {
	ComboPackageProductDiscounts ProductDiscountSlice `boil:"ComboPackageProductDiscounts" json:"ComboPackageProductDiscounts" toml:"ComboPackageProductDiscounts" yaml:"ComboPackageProductDiscounts"`
}

// NewStruct creates a new relationship struct
func (*productComboPackageR) NewStruct() *productComboPackageR {
	return &productComboPackageR{}
}

// productComboPackageL is where Load methods for each relationship are stored.
type productComboPackageL struct{}

var (
	productComboPackageAllColumns            = []string{"id", "name", "created_at", "updated_at"}
	productComboPackageColumnsWithoutDefault = []string{"name"}
	productComboPackageColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	productComboPackagePrimaryKeyColumns     = []string{"id"}
)

type (
	// ProductComboPackageSlice is an alias for a slice of pointers to ProductComboPackage.
	// This should generally be used opposed to []ProductComboPackage.
	ProductComboPackageSlice []*ProductComboPackage
	// ProductComboPackageHook is the signature for custom ProductComboPackage hook methods
	ProductComboPackageHook func(context.Context, boil.ContextExecutor, *ProductComboPackage) error

	productComboPackageQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	productComboPackageType                 = reflect.TypeOf(&ProductComboPackage{})
	productComboPackageMapping              = queries.MakeStructMapping(productComboPackageType)
	productComboPackagePrimaryKeyMapping, _ = queries.BindMapping(productComboPackageType, productComboPackageMapping, productComboPackagePrimaryKeyColumns)
	productComboPackageInsertCacheMut       sync.RWMutex
	productComboPackageInsertCache          = make(map[string]insertCache)
	productComboPackageUpdateCacheMut       sync.RWMutex
	productComboPackageUpdateCache          = make(map[string]updateCache)
	productComboPackageUpsertCacheMut       sync.RWMutex
	productComboPackageUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var productComboPackageBeforeInsertHooks []ProductComboPackageHook
var productComboPackageBeforeUpdateHooks []ProductComboPackageHook
var productComboPackageBeforeDeleteHooks []ProductComboPackageHook
var productComboPackageBeforeUpsertHooks []ProductComboPackageHook

var productComboPackageAfterInsertHooks []ProductComboPackageHook
var productComboPackageAfterSelectHooks []ProductComboPackageHook
var productComboPackageAfterUpdateHooks []ProductComboPackageHook
var productComboPackageAfterDeleteHooks []ProductComboPackageHook
var productComboPackageAfterUpsertHooks []ProductComboPackageHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ProductComboPackage) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productComboPackageBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ProductComboPackage) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productComboPackageBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ProductComboPackage) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productComboPackageBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ProductComboPackage) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productComboPackageBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ProductComboPackage) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productComboPackageAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ProductComboPackage) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productComboPackageAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ProductComboPackage) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productComboPackageAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ProductComboPackage) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productComboPackageAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ProductComboPackage) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range productComboPackageAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddProductComboPackageHook registers your hook function for all future operations.
func AddProductComboPackageHook(hookPoint boil.HookPoint, productComboPackageHook ProductComboPackageHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		productComboPackageBeforeInsertHooks = append(productComboPackageBeforeInsertHooks, productComboPackageHook)
	case boil.BeforeUpdateHook:
		productComboPackageBeforeUpdateHooks = append(productComboPackageBeforeUpdateHooks, productComboPackageHook)
	case boil.BeforeDeleteHook:
		productComboPackageBeforeDeleteHooks = append(productComboPackageBeforeDeleteHooks, productComboPackageHook)
	case boil.BeforeUpsertHook:
		productComboPackageBeforeUpsertHooks = append(productComboPackageBeforeUpsertHooks, productComboPackageHook)
	case boil.AfterInsertHook:
		productComboPackageAfterInsertHooks = append(productComboPackageAfterInsertHooks, productComboPackageHook)
	case boil.AfterSelectHook:
		productComboPackageAfterSelectHooks = append(productComboPackageAfterSelectHooks, productComboPackageHook)
	case boil.AfterUpdateHook:
		productComboPackageAfterUpdateHooks = append(productComboPackageAfterUpdateHooks, productComboPackageHook)
	case boil.AfterDeleteHook:
		productComboPackageAfterDeleteHooks = append(productComboPackageAfterDeleteHooks, productComboPackageHook)
	case boil.AfterUpsertHook:
		productComboPackageAfterUpsertHooks = append(productComboPackageAfterUpsertHooks, productComboPackageHook)
	}
}

// One returns a single productComboPackage record from the query.
func (q productComboPackageQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ProductComboPackage, error) {
	o := &ProductComboPackage{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: failed to execute a one query for product_combo_packages")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ProductComboPackage records from the query.
func (q productComboPackageQuery) All(ctx context.Context, exec boil.ContextExecutor) (ProductComboPackageSlice, error) {
	var o []*ProductComboPackage

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "orm: failed to assign all query results to ProductComboPackage slice")
	}

	if len(productComboPackageAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ProductComboPackage records in the query.
func (q productComboPackageQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to count product_combo_packages rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q productComboPackageQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "orm: failed to check if product_combo_packages exists")
	}

	return count > 0, nil
}

// ComboPackageProductDiscounts retrieves all the product_discount's ProductDiscounts with an executor via combo_package_id column.
func (o *ProductComboPackage) ComboPackageProductDiscounts(mods ...qm.QueryMod) productDiscountQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"product_discounts\".\"combo_package_id\"=?", o.ID),
	)

	query := ProductDiscounts(queryMods...)
	queries.SetFrom(query.Query, "\"product_discounts\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"product_discounts\".*"})
	}

	return query
}

// LoadComboPackageProductDiscounts allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (productComboPackageL) LoadComboPackageProductDiscounts(ctx context.Context, e boil.ContextExecutor, singular bool, maybeProductComboPackage interface{}, mods queries.Applicator) error {
	var slice []*ProductComboPackage
	var object *ProductComboPackage

	if singular {
		object = maybeProductComboPackage.(*ProductComboPackage)
	} else {
		slice = *maybeProductComboPackage.(*[]*ProductComboPackage)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &productComboPackageR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &productComboPackageR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ID) {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`product_discounts`),
		qm.WhereIn(`product_discounts.combo_package_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load product_discounts")
	}

	var resultSlice []*ProductDiscount
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice product_discounts")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on product_discounts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for product_discounts")
	}

	if len(productDiscountAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ComboPackageProductDiscounts = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &productDiscountR{}
			}
			foreign.R.ComboPackage = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ComboPackageID) {
				local.R.ComboPackageProductDiscounts = append(local.R.ComboPackageProductDiscounts, foreign)
				if foreign.R == nil {
					foreign.R = &productDiscountR{}
				}
				foreign.R.ComboPackage = local
				break
			}
		}
	}

	return nil
}

// AddComboPackageProductDiscounts adds the given related objects to the existing relationships
// of the product_combo_package, optionally inserting them as new records.
// Appends related to o.R.ComboPackageProductDiscounts.
// Sets related.R.ComboPackage appropriately.
func (o *ProductComboPackage) AddComboPackageProductDiscounts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ProductDiscount) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ComboPackageID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"product_discounts\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"combo_package_id"}),
				strmangle.WhereClause("\"", "\"", 2, productDiscountPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ComboPackageID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &productComboPackageR{
			ComboPackageProductDiscounts: related,
		}
	} else {
		o.R.ComboPackageProductDiscounts = append(o.R.ComboPackageProductDiscounts, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &productDiscountR{
				ComboPackage: o,
			}
		} else {
			rel.R.ComboPackage = o
		}
	}
	return nil
}

// SetComboPackageProductDiscounts removes all previously related items of the
// product_combo_package replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.ComboPackage's ComboPackageProductDiscounts accordingly.
// Replaces o.R.ComboPackageProductDiscounts with related.
// Sets related.R.ComboPackage's ComboPackageProductDiscounts accordingly.
func (o *ProductComboPackage) SetComboPackageProductDiscounts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ProductDiscount) error {
	query := "update \"product_discounts\" set \"combo_package_id\" = null where \"combo_package_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ComboPackageProductDiscounts {
			queries.SetScanner(&rel.ComboPackageID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.ComboPackage = nil
		}

		o.R.ComboPackageProductDiscounts = nil
	}
	return o.AddComboPackageProductDiscounts(ctx, exec, insert, related...)
}

// RemoveComboPackageProductDiscounts relationships from objects passed in.
// Removes related items from R.ComboPackageProductDiscounts (uses pointer comparison, removal does not keep order)
// Sets related.R.ComboPackage.
func (o *ProductComboPackage) RemoveComboPackageProductDiscounts(ctx context.Context, exec boil.ContextExecutor, related ...*ProductDiscount) error {
	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ComboPackageID, nil)
		if rel.R != nil {
			rel.R.ComboPackage = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("combo_package_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ComboPackageProductDiscounts {
			if rel != ri {
				continue
			}

			ln := len(o.R.ComboPackageProductDiscounts)
			if ln > 1 && i < ln-1 {
				o.R.ComboPackageProductDiscounts[i] = o.R.ComboPackageProductDiscounts[ln-1]
			}
			o.R.ComboPackageProductDiscounts = o.R.ComboPackageProductDiscounts[:ln-1]
			break
		}
	}

	return nil
}

// ProductComboPackages retrieves all the records using an executor.
func ProductComboPackages(mods ...qm.QueryMod) productComboPackageQuery {
	mods = append(mods, qm.From("\"product_combo_packages\""))
	return productComboPackageQuery{NewQuery(mods...)}
}

// FindProductComboPackage retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProductComboPackage(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ProductComboPackage, error) {
	productComboPackageObj := &ProductComboPackage{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"product_combo_packages\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, productComboPackageObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: unable to select from product_combo_packages")
	}

	return productComboPackageObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ProductComboPackage) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("orm: no product_combo_packages provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(productComboPackageColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	productComboPackageInsertCacheMut.RLock()
	cache, cached := productComboPackageInsertCache[key]
	productComboPackageInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			productComboPackageAllColumns,
			productComboPackageColumnsWithDefault,
			productComboPackageColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(productComboPackageType, productComboPackageMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(productComboPackageType, productComboPackageMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"product_combo_packages\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"product_combo_packages\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "orm: unable to insert into product_combo_packages")
	}

	if !cached {
		productComboPackageInsertCacheMut.Lock()
		productComboPackageInsertCache[key] = cache
		productComboPackageInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ProductComboPackage.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ProductComboPackage) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	productComboPackageUpdateCacheMut.RLock()
	cache, cached := productComboPackageUpdateCache[key]
	productComboPackageUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			productComboPackageAllColumns,
			productComboPackagePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("orm: unable to update product_combo_packages, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"product_combo_packages\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, productComboPackagePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(productComboPackageType, productComboPackageMapping, append(wl, productComboPackagePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update product_combo_packages row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by update for product_combo_packages")
	}

	if !cached {
		productComboPackageUpdateCacheMut.Lock()
		productComboPackageUpdateCache[key] = cache
		productComboPackageUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q productComboPackageQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all for product_combo_packages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected for product_combo_packages")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProductComboPackageSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("orm: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), productComboPackagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"product_combo_packages\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, productComboPackagePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all in productComboPackage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected all in update all productComboPackage")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ProductComboPackage) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("orm: no product_combo_packages provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(productComboPackageColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	productComboPackageUpsertCacheMut.RLock()
	cache, cached := productComboPackageUpsertCache[key]
	productComboPackageUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			productComboPackageAllColumns,
			productComboPackageColumnsWithDefault,
			productComboPackageColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			productComboPackageAllColumns,
			productComboPackagePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("orm: unable to upsert product_combo_packages, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(productComboPackagePrimaryKeyColumns))
			copy(conflict, productComboPackagePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"product_combo_packages\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(productComboPackageType, productComboPackageMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(productComboPackageType, productComboPackageMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "orm: unable to upsert product_combo_packages")
	}

	if !cached {
		productComboPackageUpsertCacheMut.Lock()
		productComboPackageUpsertCache[key] = cache
		productComboPackageUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ProductComboPackage record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ProductComboPackage) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("orm: no ProductComboPackage provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), productComboPackagePrimaryKeyMapping)
	sql := "DELETE FROM \"product_combo_packages\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete from product_combo_packages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by delete for product_combo_packages")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q productComboPackageQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("orm: no productComboPackageQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from product_combo_packages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for product_combo_packages")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProductComboPackageSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(productComboPackageBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), productComboPackagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"product_combo_packages\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, productComboPackagePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from productComboPackage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for product_combo_packages")
	}

	if len(productComboPackageAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ProductComboPackage) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindProductComboPackage(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProductComboPackageSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ProductComboPackageSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), productComboPackagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"product_combo_packages\".* FROM \"product_combo_packages\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, productComboPackagePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "orm: unable to reload all in ProductComboPackageSlice")
	}

	*o = slice

	return nil
}

// ProductComboPackageExists checks if the ProductComboPackage row exists.
func ProductComboPackageExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"product_combo_packages\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "orm: unable to check if product_combo_packages exists")
	}

	return exists, nil
}
